site_name: DiceSMS Gateway API

nav:
  - Overview: index.md
  - Getting Started: getting_started.md
  - SMS Gateway:
      - API Authentication: sms/authentication.md
      - Send SMS: sms/send_sms.md
      - SMS Delivery Report: sms/report.md
  - Transactions:
      - Report: transactions/transaction_report.md
  # - FAQs: faq.md

theme:
  name: material
  palette:
    scheme: default
    toggle:
      icon: material/brightness-7
      name: Switch to dark mode
    # scheme: slate
    # toggle:
    #   icon: material/brightness-4
    #   name: Switch to Dark mode
    primary: light
    accent: indigo
  logo: assets/dice_logo.png
  favicon: assets/favicon.ico
  features:
    - navigation.path

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/Ajna-Lab
    - icon: fontawesome/brands/linkedin
      link: https://linkedin.com/company/ajna-lab

copyright: Copyright &copy; 2025 Ajnalab Pvt Ltd. All rights reserved.